server:
  port: ${PORT:9191}
  
spring:
  datasource:
    initialize : false
  sleuth:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true
